FROM {{IMAGE}}
WORKDIR /app
{{NPM_HARDENING}}
# Common start commands you can uncomment to customize per-project
# CMD ["bash"]
# CMD ["bash","-l"]
# CMD ["sh"]
# CMD ["node","server.js"]
# CMD ["python","main.py"]
CMD ["npm","start"]
